SYSCALL_DEF(close, ARG_DEC);
#ifdef TARGET_NR_open
SYSCALL_DEF(open, ARG_STR, ARG_OPENFLAG, ARG_MODEFLAG);
#endif
SYSCALL_DEF(openat, ARG_ATDIRFD, ARG_STR, ARG_OPENFLAG, ARG_MODEFLAG);
SYSCALL_DEF(read, ARG_DEC, ARG_PTR, ARG_DEC);
#ifdef TARGET_NR_readlink
SYSCALL_DEF(readlink, ARG_STR, ARG_PTR, ARG_DEC);
#endif
#ifdef TARGET_NR_readlinkat
SYSCALL_DEF(readlinkat, ARG_ATDIRFD, ARG_STR, ARG_PTR, ARG_DEC);
#endif
SYSCALL_DEF(write, ARG_DEC, ARG_PTR, ARG_DEC);
SYSCALL_DECL(preadv, args_preadv_pwritev, impl_preadv, NULL, NULL, ARG_DEC, ARG_PTR, ARG_DEC, ARG_DEC64);
SYSCALL_DECL(pwritev, args_preadv_pwritev, impl_pwritev, NULL, NULL, ARG_DEC, ARG_PTR, ARG_DEC, ARG_DEC64);
SYSCALL_DEF(readv, ARG_DEC, ARG_PTR, ARG_DEC);
SYSCALL_DEF(writev, ARG_DEC, ARG_PTR, ARG_DEC);
SYSCALL_DECL(pread64, args_pread64_pwrite64, impl_pread64, NULL, NULL, ARG_DEC, ARG_PTR, ARG_DEC, ARG_DEC64);
SYSCALL_DECL(pwrite64, args_pread64_pwrite64, impl_pwrite64, NULL, NULL, ARG_DEC, ARG_PTR, ARG_DEC, ARG_DEC64);
